# -*- coding: utf-8 -*-

from PyQt5 import QtCore, QtGui, QtWidgets
from scapy.all import *
from threading import Thread, Event
from time import sleep
import netifaces
import logging

class SnifferThread(QtCore.QThread):
        connection = QtCore.pyqtSignal(list)
        def print_packet(self,packet):
            ip_layer = packet.getlayer(IP)
            packet_length = str(len(packet))
            row_Data = [str(packet.time),str(ip_layer.src),str(ip_layer.dst)]
            #print("Raw packet data: " + str(packet))
            #print(packet.show())
            #print(packet.show2())
            #print(packet.display())
            if(packet.haslayer('TCP')):
                row_Data.append('TCP')
            elif(packet.haslayer('UDP')):
                row_Data.append('UDP')
            elif(packet.haslayer('ICMP')):
                row_Data.append('ICMP')
                    
            row_Data.append(packet_length)
            row_Data.append('info here')
            self.connection.emit(row_Data)
    
        def run(self):
            sniff(iface='wlo1', filter="ip", prn=self.print_packet)



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1094, 771)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Filters = QtWidgets.QTextEdit(self.centralwidget)
        self.Filters.setGeometry(QtCore.QRect(20, 50, 831, 31))
        self.Filters.setObjectName("Filters")
        self.searchButton = QtWidgets.QPushButton(self.centralwidget)
        self.searchButton.setGeometry(QtCore.QRect(980, 50, 88, 31))
        self.searchButton.setObjectName("searchButton")
        self.Packets = QtWidgets.QTableWidget(self.centralwidget)
        self.Packets.setGeometry(QtCore.QRect(20, 90, 1051, 251))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Packets.sizePolicy().hasHeightForWidth())
        self.Packets.setSizePolicy(sizePolicy)
        self.Packets.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Packets.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Packets.setLineWidth(1)
        self.Packets.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.Packets.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.Packets.setAlternatingRowColors(False)
        self.Packets.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.Packets.setRowCount(0)
        self.Packets.setColumnCount(6)
        self.Packets.setObjectName("Packets")
        item = QtWidgets.QTableWidgetItem()
        self.Packets.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Packets.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Packets.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Packets.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.Packets.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.Packets.setHorizontalHeaderItem(5, item)
        self.Packets.horizontalHeader().setCascadingSectionResizes(False)
        self.Packets.horizontalHeader().setDefaultSectionSize(160)
        self.Packets.horizontalHeader().setMinimumSectionSize(23)
        self.Packets.horizontalHeader().setSortIndicatorShown(False)
        self.Packets.horizontalHeader().setStretchLastSection(True)
        self.Packets.verticalHeader().setStretchLastSection(True)
        self.packetInfo = QtWidgets.QTreeWidget(self.centralwidget)
        self.packetInfo.setGeometry(QtCore.QRect(20, 360, 1051, 191))
        self.packetInfo.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.packetInfo.setAlternatingRowColors(False)
        self.packetInfo.setObjectName("packetInfo")
        item_0 = QtWidgets.QTreeWidgetItem(self.packetInfo)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.packetInfo)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.packetInfo)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        self.packetHex = QtWidgets.QTextBrowser(self.centralwidget)
        self.packetHex.setGeometry(QtCore.QRect(20, 570, 1051, 131))
        self.packetHex.setObjectName("packetHex")
        self.interfaceLabel = QtWidgets.QLabel(self.centralwidget)
        self.interfaceLabel.setGeometry(QtCore.QRect(20, 10, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.interfaceLabel.setFont(font)
        self.interfaceLabel.setObjectName("interfaceLabel")
        self.interfacesList = QtWidgets.QComboBox(self.centralwidget)
        self.interfacesList.setGeometry(QtCore.QRect(160, 10, 801, 31))
        self.interfacesList.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.interfacesList.setAutoFillBackground(False)
        self.interfacesList.setObjectName("interfacesList")
        self.interfacesList.addItems(netifaces.interfaces())
        self.captureButton = QtWidgets.QPushButton(self.centralwidget)
        self.captureButton.setGeometry(QtCore.QRect(980, 10, 88, 31))
        self.captureButton.setObjectName("captureButton")
        self.clearFiltersButton = QtWidgets.QPushButton(self.centralwidget)
        self.clearFiltersButton.setGeometry(QtCore.QRect(870, 50, 91, 31))
        self.clearFiltersButton.setObjectName("clearFiltersButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1094, 25))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuCapture = QtWidgets.QMenu(self.menubar)
        self.menuCapture.setObjectName("menuCapture")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        self.menuFilters = QtWidgets.QMenu(self.menubar)
        self.menuFilters.setObjectName("menuFilters")
        self.menuFilter_by_type = QtWidgets.QMenu(self.menuFilters)
        self.menuFilter_by_type.setObjectName("menuFilter_by_type")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionStart_Capture = QtWidgets.QAction(MainWindow)
        self.actionStart_Capture.setObjectName("actionStart_Capture")
        self.actionStop_Capture = QtWidgets.QAction(MainWindow)
        self.actionStop_Capture.setObjectName("actionStop_Capture")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionInstructions = QtWidgets.QAction(MainWindow)
        self.actionInstructions.setObjectName("actionInstructions")
        self.actionUDP = QtWidgets.QAction(MainWindow)
        self.actionUDP.setCheckable(True)
        self.actionUDP.setObjectName("actionUDP")
        self.actionTCP = QtWidgets.QAction(MainWindow)
        self.actionTCP.setCheckable(True)
        self.actionTCP.setObjectName("actionTCP")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionExit)
        self.menuCapture.addAction(self.actionStart_Capture)
        self.menuCapture.addAction(self.actionStop_Capture)
        self.menuAbout.addAction(self.actionInstructions)
        self.menuAbout.addAction(self.actionAbout)
        self.menuFilter_by_type.addAction(self.actionUDP)
        self.menuFilter_by_type.addAction(self.actionTCP)
        self.menuFilters.addAction(self.menuFilter_by_type.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuCapture.menuAction())
        self.menubar.addAction(self.menuFilters.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        logging.basicConfig(filename="sniffer.log", format='%(asctime)s %(message)s', filemode='a') 
        self.logger=logging.getLogger() 
        self.logger.setLevel(logging.DEBUG)
        self.logger.info('Interface started!')
        
        self.actionExit.triggered.connect(sys.exit)
        self.captureButton.clicked.connect(self.capture_btn_clicked)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Packet Sniffer"))
        self.Filters.setPlaceholderText(_translate("MainWindow", "Filters"))
        self.searchButton.setText(_translate("MainWindow", "Apply"))
        item = self.Packets.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Time"))
        item = self.Packets.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Source"))
        item = self.Packets.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Destination"))
        item = self.Packets.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Protocol"))
        item = self.Packets.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Length"))
        item = self.Packets.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Info"))
        __sortingEnabled = self.packetInfo.isSortingEnabled()
        self.packetInfo.setSortingEnabled(False)
        self.packetInfo.topLevelItem(0).setText(0, _translate("MainWindow", "IP"))
        self.packetInfo.topLevelItem(0).child(0).setText(0, _translate("MainWindow", "New Subitem"))
        self.packetInfo.topLevelItem(1).setText(0, _translate("MainWindow", "HTTP"))
        self.packetInfo.topLevelItem(1).child(0).setText(0, _translate("MainWindow", "New Subitem"))
        self.packetInfo.topLevelItem(2).setText(0, _translate("MainWindow", "Transmission control protocol"))
        self.packetInfo.topLevelItem(2).child(0).setText(0, _translate("MainWindow", "New Subitem"))
        self.packetInfo.setSortingEnabled(__sortingEnabled)
        self.interfaceLabel.setText(_translate("MainWindow", "Choose Interface:"))
        self.interfacesList.setStatusTip(_translate("MainWindow", "Choose Interface for packets capture"))
        self.interfacesList.setItemText(0, _translate("MainWindow", "Select Interface for Capturing Packets"))
        self.captureButton.setText(_translate("MainWindow", "Capture"))
        self.clearFiltersButton.setText(_translate("MainWindow", "Clear"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuCapture.setTitle(_translate("MainWindow", "Capture"))
        self.menuAbout.setTitle(_translate("MainWindow", "Help"))
        self.menuFilters.setTitle(_translate("MainWindow", "Filters"))
        self.menuFilter_by_type.setTitle(_translate("MainWindow", "Filter by type"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave.setStatusTip(_translate("MainWindow", "Saves a file"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionStart_Capture.setText(_translate("MainWindow", "Start Capture"))
        self.actionStop_Capture.setText(_translate("MainWindow", "Stop Capture"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionInstructions.setText(_translate("MainWindow", "Instructions"))
        self.actionUDP.setText(_translate("MainWindow", "UDP"))
        self.actionTCP.setText(_translate("MainWindow", "TCP"))

    def getPackets(self):
        return self.Packets

    current_row = 0
    def addRowData(self,Data):
        self.Packets.insertRow(self.current_row)
        column_number = 0
        for packet_Data in Data:
            self.Packets.setItem(self.current_row,column_number,QtWidgets.QTableWidgetItem(str(packet_Data)))
            column_number = column_number + 1
        self.current_row = self.current_row + 1


    def capture_btn_clicked(self):
        interface_chosen = str(self.interfacesList.currentText())
        try:
            if(interface_chosen=='Select Interface for Capturing Packets'):
                self.msg = QtWidgets.QMessageBox()
                self.msg.setIcon(QtWidgets.QMessageBox.Critical)
                self.msg.setWindowTitle("Interface error!")
                self.msg.setText("Not a valid capture interface! \nPlease choose a valid interface.")
                self.msg.exec_()
            else:
                self.captureButton.setText("Stop")
                self.Thread = SnifferThread()
                self.Thread.connection.connect(self.addRowData)
                self.Thread.start()

        except:
            self.logger.error('Wrong interface selected!')
            self.captureButton.disconnect()
             

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
