# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Packet_Sniffer.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!

import sys
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1082, 771)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Filters = QtWidgets.QTextEdit(self.centralwidget)
        self.Filters.setGeometry(QtCore.QRect(20, 50, 821, 31))
        self.Filters.setObjectName("Filters")
        self.searchButton = QtWidgets.QPushButton(self.centralwidget)
        self.searchButton.setGeometry(QtCore.QRect(970, 50, 88, 31))
        self.searchButton.setObjectName("searchButton")
        self.Packets = QtWidgets.QTableWidget(self.centralwidget)
        self.Packets.setGeometry(QtCore.QRect(20, 90, 1041, 251))
        self.Packets.setRowCount(0)
        self.Packets.setColumnCount(7)
        self.Packets.setObjectName("Packets")
        item = QtWidgets.QTableWidgetItem()
        self.Packets.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Packets.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Packets.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Packets.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.Packets.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.Packets.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.Packets.setHorizontalHeaderItem(6, item)
        self.packetInfo = QtWidgets.QTreeWidget(self.centralwidget)
        self.packetInfo.setGeometry(QtCore.QRect(20, 360, 1041, 191))
        self.packetInfo.setObjectName("packetInfo")
        item_0 = QtWidgets.QTreeWidgetItem(self.packetInfo)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.packetInfo)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.packetInfo)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.packetInfo)
        item_0 = QtWidgets.QTreeWidgetItem(self.packetInfo)
        self.packetHex = QtWidgets.QTextBrowser(self.centralwidget)
        self.packetHex.setGeometry(QtCore.QRect(20, 570, 1041, 131))
        self.packetHex.setObjectName("packetHex")
        self.interfaceLabel = QtWidgets.QLabel(self.centralwidget)
        self.interfaceLabel.setGeometry(QtCore.QRect(20, 10, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.interfaceLabel.setFont(font)
        self.interfaceLabel.setObjectName("interfaceLabel")
        self.interfacesList = QtWidgets.QComboBox(self.centralwidget)
        self.interfacesList.setGeometry(QtCore.QRect(160, 10, 791, 31))
        self.interfacesList.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.interfacesList.setAutoFillBackground(False)
        self.interfacesList.setObjectName("interfacesList")
        self.interfacesList.addItem("")
        self.captureButton = QtWidgets.QPushButton(self.centralwidget)
        self.captureButton.setGeometry(QtCore.QRect(970, 10, 88, 31))
        self.captureButton.setObjectName("captureButton")
        self.clearFiltersButton = QtWidgets.QPushButton(self.centralwidget)
        self.clearFiltersButton.setGeometry(QtCore.QRect(860, 50, 91, 31))
        self.clearFiltersButton.setObjectName("clearFiltersButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1082, 25))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuCapture = QtWidgets.QMenu(self.menubar)
        self.menuCapture.setObjectName("menuCapture")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        self.menuFilters = QtWidgets.QMenu(self.menubar)
        self.menuFilters.setObjectName("menuFilters")
        self.menuFilter_by_type = QtWidgets.QMenu(self.menuFilters)
        self.menuFilter_by_type.setObjectName("menuFilter_by_type")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionStart_Capture = QtWidgets.QAction(MainWindow)
        self.actionStart_Capture.setObjectName("actionStart_Capture")
        self.actionStop_Capture = QtWidgets.QAction(MainWindow)
        self.actionStop_Capture.setObjectName("actionStop_Capture")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionInstructions = QtWidgets.QAction(MainWindow)
        self.actionInstructions.setObjectName("actionInstructions")
        self.actionUDP = QtWidgets.QAction(MainWindow)
        self.actionUDP.setCheckable(True)
        self.actionUDP.setObjectName("actionUDP")
        self.actionTCP = QtWidgets.QAction(MainWindow)
        self.actionTCP.setCheckable(True)
        self.actionTCP.setObjectName("actionTCP")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionExit)
        self.menuCapture.addAction(self.actionStart_Capture)
        self.menuCapture.addAction(self.actionStop_Capture)
        self.menuAbout.addAction(self.actionInstructions)
        self.menuAbout.addAction(self.actionAbout)
        self.menuFilter_by_type.addAction(self.actionUDP)
        self.menuFilter_by_type.addAction(self.actionTCP)
        self.menuFilters.addAction(self.menuFilter_by_type.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuCapture.menuAction())
        self.menubar.addAction(self.menuFilters.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.actionExit.triggered.connect(sys.exit)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Packet Sniffer"))
        self.Filters.setPlaceholderText(_translate("MainWindow", "Filters"))
        self.searchButton.setText(_translate("MainWindow", "Apply"))
        item = self.Packets.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "No"))
        item = self.Packets.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Time"))
        item = self.Packets.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Source"))
        item = self.Packets.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Destination"))
        item = self.Packets.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Protocol"))
        item = self.Packets.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Length"))
        item = self.Packets.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Info"))
        __sortingEnabled = self.packetInfo.isSortingEnabled()
        self.packetInfo.setSortingEnabled(False)
        self.packetInfo.topLevelItem(0).setText(0, _translate("MainWindow", "IP"))
        self.packetInfo.topLevelItem(0).child(0).setText(0, _translate("MainWindow", "New Subitem"))
        self.packetInfo.topLevelItem(1).setText(0, _translate("MainWindow", "HTTP"))
        self.packetInfo.topLevelItem(1).child(0).setText(0, _translate("MainWindow", "New Subitem"))
        self.packetInfo.topLevelItem(2).setText(0, _translate("MainWindow", "Transmission control protocol"))
        self.packetInfo.topLevelItem(2).child(0).setText(0, _translate("MainWindow", "New Subitem"))
        self.packetInfo.topLevelItem(3).setText(0, _translate("MainWindow", "New Item"))
        self.packetInfo.topLevelItem(4).setText(0, _translate("MainWindow", "New Item"))
        self.packetInfo.setSortingEnabled(__sortingEnabled)
        self.interfaceLabel.setText(_translate("MainWindow", "Choose Interface:"))
        self.interfacesList.setStatusTip(_translate("MainWindow", "Choose Interface for packets capture"))
        self.interfacesList.setItemText(0, _translate("MainWindow", "Test"))
        self.captureButton.setText(_translate("MainWindow", "Capture"))
        self.clearFiltersButton.setText(_translate("MainWindow", "Clear"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuCapture.setTitle(_translate("MainWindow", "Capture"))
        self.menuAbout.setTitle(_translate("MainWindow", "Help"))
        self.menuFilters.setTitle(_translate("MainWindow", "Filters"))
        self.menuFilter_by_type.setTitle(_translate("MainWindow", "Filter by type"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave.setStatusTip(_translate("MainWindow", "Saves a file"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionStart_Capture.setText(_translate("MainWindow", "Start Capture"))
        self.actionStop_Capture.setText(_translate("MainWindow", "Stop Capture"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionInstructions.setText(_translate("MainWindow", "Instructions"))
        self.actionUDP.setText(_translate("MainWindow", "UDP"))
        self.actionTCP.setText(_translate("MainWindow", "TCP"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
